#!/bin/bash
# Simple launcher program for gnome-terminal.
# I like to launch terminals from the command line instead of icons.
# J. Cutter 

# Set names for gnome-terminal profiles to use -s, -m, and -l options.
# Create these profiles in gnome-terminal on your own.

SMALL="Blue_Small"
MEDIUM="Blue_Medium"
LARGE="Blue_Large"

NAME=$(basename $0)

function usage {
  echo "USAGE: $NAME [-s|-m|-l] [-h] [-f filename] [host1 [host2..hostN]]"
  echo
  echo "  -s  Select small profile."
  echo "  -m  Select medium profile."
  echo "  -s  Select large profile."
  echo
  echo "  -f  Specify a file to read hosts from."
  echo
  echo "  -h  This usage statement."
  echo
  exit 1
}

while getopts lmshf: OPT
do
  case $OPT in
    s) PROFILE="$SMALL" ;;
    m) PROFILE="$MEDIUM" ;;
    l) PROFILE="$LARGE" ;;
    f) FILE=$OPTARG ;;
    *) usage ;;
  esac
done

shift $((OPTIND-1))

if [ -z "$PROFILE" ]
then
  PROFILE="Blue"
fi

if [ -n "$FILE" ]
then
  if [[ -f "$FILE" && -r "$FILE" ]]
  then
    SERVERS=$(egrep -v "^#" $FILE)
  else
    echo "File $FILE not found or not readable."
  fi
else
  SERVERS=$*
fi

if [ -n "$SERVERS" ]
then
  for i in $SERVERS
  do
    gnome-terminal --profile="$PROFILE" -e "ssh $i"
  done
else
  gnome-terminal --profile="$PROFILE"
fi
