#!/bin/bash
# Simple launcher program for gnome-terminal.
# I like to launch terminals from the command line instead of icons.
# J. Cutter 

# Set names for gnome-terminal profile to use.
PROFILE="Blue"

# Create these profiles in gnome-terminal on your own.

SMALL="80x40"
MEDIUM="100x50"
LARGE="120x60"

NAME=$(basename $0)

function usage {
  echo "USAGE: $NAME [-s|-m|-l] [-h] [-f filename] [host1 [host2..hostN]]"
  echo
  echo "  -s  Select small profile."
  echo "  -m  Select medium profile."
  echo "  -s  Select large profile."
  echo
  echo "  -f  Specify a file to read hosts from."
  echo
  echo "  -h  This usage statement."
  echo
  exit 1
}

while getopts lmshf: OPT
do
  case $OPT in
    s) SIZE="$SMALL" ;;
    m) SIZE="$MEDIUM" ;;
    l) SIZE="$LARGE" ;;
    f) FILE=$OPTARG ;;
    *) usage ;;
  esac
done

shift $((OPTIND-1))

if [ -z "$SIZE" ]
then
  SIZE=$SMALL
fi

if [ -n "$FILE" ]
then
  if [[ -f "$FILE" && -r "$FILE" ]]
  then
    SERVERS=$(egrep -v "^#" $FILE)
  else
    echo "File $FILE not found or not readable."
  fi
else
  SERVERS=$*
fi

if [ -n "$SERVERS" ]
then
  for i in $SERVERS
  do
    gnome-terminal --profile="$PROFILE" --geometry=$SIZE -e "ssh $i"
  done
else
  gnome-terminal --profile="$PROFILE" --geometry=$SIZE
fi
